name: hoppy_club
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.2
    
  flutter_launcher_icons: ^0.14.1
  google_fonts: ^6.2.1
  
  shared_preferences: ^2.1.1
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launchicon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/launchicon.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/launchicon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/launchicon.jpeg"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/profiles/
    - assets/icons/
    - assets/hobbies/
    - assets/videos/
    - assets/fonts/
  
  
